name:  Generate documentation, Build, Test and upload coverage report

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          pytest -v
      - name: Run test with coverage report and generate documentation
        run: |
          coverage run --source=. -m pytest && coverage xml && python3 -m pdoc ./src/* -o ./docs/
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          token: dd9b07c3-08b1-41ae-a90c-8b4ea8b242f7